name = "generator"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["AJ Ianozi"]
maintainers = ["AJ Ianozi <aj@ianozi.com>"]
maintainers-logins = ["aj-ianozi"]

executables = ["generator"]
